# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=50)),
                ('owner', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=30)),
                ('height', models.CharField(blank=True, max_length=30, null=True)),
                ('width', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(blank=True, height_field='height', null=True, upload_to='clinic_photos/', width_field='width')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='locationn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('county_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='county_images', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MyPatients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='New_Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_specialty', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_no', models.IntegerField(null=True)),
                ('photo', models.ImageField(blank=True, height_field='height', null=True, upload_to='dr_profile_images/', width_field='width')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('doctor', models.NullBooleanField(default=None)),
                ('second_name', models.CharField(blank=True, max_length=30)),
                ('education', models.CharField(blank=True, max_length=500, null=True)),
                ('professional_membership', models.CharField(blank=True, max_length=500, null=True)),
                ('board_certifications', models.CharField(blank=True, max_length=500, null=True)),
                ('professional_awards', models.CharField(blank=True, max_length=500, null=True)),
                ('professional_biography', models.TextField(blank=True, max_length=1500, null=True)),
                ('doctor_activate', models.BooleanField(default=False)),
                ('patient', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile_pic_thumbnails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sd', 'standard_images'), ('micro', 'images_for_phones')], default='sd', max_length=20)),
                ('height', models.CharField(blank=True, max_length=30, null=True)),
                ('width', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(blank=True, height_field='height', null=True, upload_to='dr_profile_pic/', width_field='width')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sd', 'standard_images'), ('micro', 'images_for_phones')], default='sd', max_length=20)),
                ('building_height', models.CharField(blank=True, max_length=30, null=True)),
                ('building_width', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(blank=True, height_field='building_height', null=True, upload_to='thumbnail_clinic_photos/', width_field='building_width')),
                ('clinic_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.ClinicPhotos')),
            ],
        ),
        migrations.AddField(
            model_name='new_specialty',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mypatients',
            name='dr',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mypatients',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doc_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.locationn'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
