# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20180324_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
