# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20180326_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
